// Code generated by github.com/fjl/gencodec. DO NOT EDIT.

package types

import (
	"encoding/json"
	"errors"

	"github.com/insight-chain/inb-go/common"
	"github.com/insight-chain/inb-go/common/hexutil"
)

var _ = (*receiptMarshaling)(nil)

// MarshalJSON marshals as JSON.
func (r Receipt) MarshalJSON() ([]byte, error) {
	type Receipt struct {
		PostState         hexutil.Bytes  `json:"root"`
		Status            hexutil.Uint64 `json:"status"`
		CumulativeNetUsed hexutil.Uint64 `json:"cumulativeNetUsed" gencodec:"required"`
		Bloom             Bloom          `json:"logsBloom"         gencodec:"required"`
		Logs              []*Log         `json:"logs"              gencodec:"required"`
		TxHash            common.Hash    `json:"transactionHash" gencodec:"required"`
		ContractAddress   common.Address `json:"contractAddress"`
		NetUsed           hexutil.Uint64 `json:"netUsed" gencodec:"required"`
		IncomeClaimed     hexutil.Uint64 `json:"incomeClaimed" gencodec:"required"`
	}
	var enc Receipt
	enc.PostState = r.PostState
	enc.Status = hexutil.Uint64(r.Status)
	enc.CumulativeNetUsed = hexutil.Uint64(r.CumulativeNetUsed)
	enc.Bloom = r.Bloom
	enc.Logs = r.Logs
	enc.TxHash = r.TxHash
	enc.ContractAddress = r.ContractAddress
	enc.NetUsed = hexutil.Uint64(r.NetUsed)
	enc.IncomeClaimed = hexutil.Uint64(r.IncomeClaimed)
	return json.Marshal(&enc)
}

// UnmarshalJSON unmarshals from JSON.
func (r *Receipt) UnmarshalJSON(input []byte) error {
	type Receipt struct {
		PostState         *hexutil.Bytes  `json:"root"`
		Status            *hexutil.Uint64 `json:"status"`
		CumulativeNetUsed *hexutil.Uint64 `json:"cumulativeNetUsed" gencodec:"required"`
		Bloom             *Bloom          `json:"logsBloom"         gencodec:"required"`
		Logs              []*Log          `json:"logs"              gencodec:"required"`
		TxHash            *common.Hash    `json:"transactionHash" gencodec:"required"`
		ContractAddress   *common.Address `json:"contractAddress"`
		NetUsed           *hexutil.Uint64 `json:"netUsed" gencodec:"required"`
		IncomeClaimed     *hexutil.Uint64 `json:"incomeClaimed" gencodec:"required"`
	}
	var dec Receipt
	if err := json.Unmarshal(input, &dec); err != nil {
		return err
	}
	if dec.PostState != nil {
		r.PostState = *dec.PostState
	}
	if dec.Status != nil {
		r.Status = uint64(*dec.Status)
	}
	if dec.CumulativeNetUsed == nil {
		return errors.New("missing required field 'cumulativeNetUsed' for Receipt")
	}
	r.CumulativeNetUsed = uint64(*dec.CumulativeNetUsed)
	if dec.Bloom == nil {
		return errors.New("missing required field 'logsBloom' for Receipt")
	}
	r.Bloom = *dec.Bloom
	if dec.Logs == nil {
		return errors.New("missing required field 'logs' for Receipt")
	}
	r.Logs = dec.Logs
	if dec.TxHash == nil {
		return errors.New("missing required field 'transactionHash' for Receipt")
	}
	r.TxHash = *dec.TxHash
	if dec.ContractAddress != nil {
		r.ContractAddress = *dec.ContractAddress
	}
	if dec.NetUsed == nil {
		return errors.New("missing required field 'netUsed' for Receipt")
	}
	r.NetUsed = uint64(*dec.NetUsed)
	if dec.IncomeClaimed == nil {
		return errors.New("missing required field 'incomeClaimed' for Receipt")
	}
	r.IncomeClaimed = uint64(*dec.IncomeClaimed)
	return nil
}
