// Code generated by github.com/fjl/gencodec. DO NOT EDIT.

package core

import (
	"encoding/json"
	"errors"
	"math/big"

	"github.com/insight-chain/inb-go/common"
	"github.com/insight-chain/inb-go/common/hexutil"
	"github.com/insight-chain/inb-go/common/math"
	"github.com/insight-chain/inb-go/core/types"
	"github.com/insight-chain/inb-go/params"
)

var _ = (*genesisSpecMarshaling)(nil)

func (g Genesis) MarshalJSON() ([]byte, error) {
	type Genesis struct {
		Config           *params.ChainConfig                         `json:"config"`
		Nonce            math.HexOrDecimal64                         `json:"nonce"`
		Timestamp        math.HexOrDecimal64                         `json:"timestamp"`
		ExtraData        hexutil.Bytes                               `json:"extraData"`
		NetLimit         math.HexOrDecimal64                         `json:"netLimit"   gencodec:"required"`
		Difficulty       *math.HexOrDecimal256                       `json:"difficulty" gencodec:"required"`
		Mixhash          common.Hash                                 `json:"mixHash"`
		Coinbase         common.Address                              `json:"coinbase"`
		Alloc            map[common.UnprefixedAddress]GenesisAccount `json:"alloc"      gencodec:"required"`
		Number           math.HexOrDecimal64                         `json:"number"`
		NetUsed          math.HexOrDecimal64                         `json:"netUsed"`
		ParentHash       common.Hash                                 `json:"parentHash"`
		SpecialConsensus types.SpecialConsensus                      `json:"specialConsensus" gencodec:"required"`
	}
	var enc Genesis
	enc.Config = g.Config
	enc.Nonce = math.HexOrDecimal64(g.Nonce)
	enc.Timestamp = math.HexOrDecimal64(g.Timestamp)
	enc.ExtraData = g.ExtraData
	enc.NetLimit = math.HexOrDecimal64(g.NetLimit)
	enc.Difficulty = (*math.HexOrDecimal256)(g.Difficulty)
	enc.Mixhash = g.Mixhash
	enc.Coinbase = g.Coinbase
	if g.Alloc != nil {
		enc.Alloc = make(map[common.UnprefixedAddress]GenesisAccount, len(g.Alloc))
		for k, v := range g.Alloc {
			enc.Alloc[common.UnprefixedAddress(k)] = v
		}
	}
	enc.Number = math.HexOrDecimal64(g.Number)
	enc.NetUsed = math.HexOrDecimal64(g.NetUsed)
	enc.ParentHash = g.ParentHash
	enc.SpecialConsensus = g.SpecialConsensus //2019.7.23 inb by ghy
	return json.Marshal(&enc)
}

type Genesiss struct {
	Config           *params.ChainConfig                         `json:"config"`
	Nonce            *math.HexOrDecimal64                        `json:"nonce"`
	Timestamp        *math.HexOrDecimal64                        `json:"timestamp"`
	ExtraData        *hexutil.Bytes                              `json:"extraData"`
	NetLimit         *math.HexOrDecimal64                        `json:"netLimit"   gencodec:"required"`
	Difficulty       *math.HexOrDecimal256                       `json:"difficulty" gencodec:"required"`
	Mixhash          *common.Hash                                `json:"mixHash"`
	Coinbase         *common.Address                             `json:"coinbase"`
	Alloc            map[common.UnprefixedAddress]GenesisAccount `json:"alloc"      gencodec:"required"`
	Number           *math.HexOrDecimal64                        `json:"number"`
	NetUsed          *math.HexOrDecimal64                        `json:"netUsed"`
	ParentHash       *common.Hash                                `json:"parentHash"`
	SpecialConsensus types.SpecialConsensus                      `json:"specialConsensus" gencodec:"required"` //2019.7.23 inb by ghy
}

func (g *Genesis) UnmarshalJSON(input []byte) error {
	var dec Genesiss
	if err := Unmarshal(input, &dec); err != nil {
		return err
	}
	if dec.Config != nil {
		g.Config = dec.Config
	}
	if dec.Nonce != nil {
		g.Nonce = uint64(*dec.Nonce)
	}
	if dec.Timestamp != nil {
		g.Timestamp = uint64(*dec.Timestamp)
	}
	if dec.ExtraData != nil {
		g.ExtraData = *dec.ExtraData
	}
	if dec.NetLimit == nil {
		return errors.New("missing required field 'netLimit' for Genesis")
	}
	g.NetLimit = uint64(*dec.NetLimit)
	if dec.Difficulty == nil {
		return errors.New("missing required field 'difficulty' for Genesis")
	}
	g.Difficulty = (*big.Int)(dec.Difficulty)
	if dec.Mixhash != nil {
		g.Mixhash = *dec.Mixhash
	}
	if dec.Coinbase != nil {
		g.Coinbase = *dec.Coinbase
	}
	if dec.Alloc == nil {
		return errors.New("missing required field 'alloc' for Genesis")
	}
	g.Alloc = make(GenesisAlloc, len(dec.Alloc))
	for k, v := range dec.Alloc {
		g.Alloc[common.Address(k)] = v
	}
	if dec.Number != nil {
		g.Number = uint64(*dec.Number)
	}
	if dec.NetUsed != nil {
		g.NetUsed = uint64(*dec.NetUsed)
	}
	if dec.ParentHash != nil {
		g.ParentHash = *dec.ParentHash
	}
	//2019.7.23 inb by ghy
	if dec.SpecialConsensus.SpecialConsensusAddress != nil || dec.SpecialConsensus.SpecialNumer != nil {
		g.SpecialConsensus = dec.SpecialConsensus
	}
	return nil
}
